/**
 * generated by Xtext 2.25.0
 */
package org.example.domainmodel.domainmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XImport Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.domainmodel.domainmodel.DomainmodelPackage#getXImportDeclaration()
 * @model
 * @generated
 */
public interface XImportDeclaration extends org.eclipse.xtext.xtype.XImportDeclaration
{
} // XImportDeclaration
